remote_theme: benc-uk/theme-msdark
title: Azure Icon Collection
favicon: http://benc-uk.github.io/icon-collection/azure-dotcom/blockchain.svg
buttons:
  - text: Download All
    href: https://github.com/benc-uk/icon-collection/archive/master.zip